### ISSUE TITLE
(Feature suggestion) Epub Downloader

### ISSUE THREAD

**Issue by xeolod** [manga-download/haruneko#166]
To be able to download epub's from a website.

**Comment by Sheepux** [comment]
Do you have any website example ?

**Comment by Sheepux** [comment]
So it's not "epub" websites but "novel" websites.
And you'd like epub support, something that already exists within hakuneko. Ex: wuxia is already supported
Cloudflare is another topic that is being worked on.
I'll close this issue as it's a feature coverage that already exists
