### ISSUE TITLE
Remember window size & position

### ISSUE THREAD

**Issue by Sheepux** [manga-download/haruneko#18]
Remember window size & position on startup
https://github.com/manga-download/hakuneko/issues/3046

**Comment by Sheepux** [comment]
OK for Windows by specifying an ID in the NWjs window.
Looks like it's not working fine for Ronny

**Comment by Pierre-Monier** [comment]
This is working on Linux (Ubuntu 20.10, Wayland)

**Comment by Sheepux** [comment]
@ronny1982 do you still have the size & position issue on MacOS ?

**Comment by ronny1982** [comment]
Don't know, was on my old MacBook and i forgot what the issue was snd therefore how to reproduce it, so probably no longer exist
