### ISSUE TITLE
Download from context menu not working

### ISSUE THREAD

**Issue by isyfalana** [manga-download/haruneko#187]
There no 'download new chapter' button, luckily I found answer on closed issue [https://github.com/manga-download/haruneko/issues/175](url) by multiple select shift / ctrl, but it not work.
I try View, Flag, and its work, but 'Download' and 'Download selecteds' not work.
I have try exe version and nodejs version.

**Comment by MikeZeDev** [comment]
Haruneko is still WIP, Missing features are to be expected ^^. This one hasnt been coded yet. Thanks for your concern
