### ISSUE TITLE
Handle websites with url that keeps changing

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/haruneko#193]
Many websites have a "portal page" that gives or redirect to the real domain. Most of the time its increasing numbers : newtoki144.com, newtoki145.com etc...

In other words, allow a plugin to reassign the url at runtime, or some workaround.
Maybe  a private property _realurl set in Initialize, and a getter for "URI" that returns _realurl after initialize was run?

**Comment by MikeZeDev** [comment]
https://cdn.discordapp.com/attachments/581631164398174208/1143865177289277460/image.png

Ads are a problem, and its a pain to maintain a blacklist

**Comment by ronny1982** [comment]
The desired behavior can already be achieved by assigning `this.URI.href = '...'` in the `Initialize()` method of the website plugin

**Comment by MikeZeDev** [comment]
> The desired behavior can already be achieved by assigning `this.URI.href = '...'` in the `Initialize()` method of the website plugin

Isnt the property readonly? Last time i checked it was.

**Comment by ronny1982** [comment]
> > The desired behavior can already be achieved by assigning `this.URI.href = '...'` in the `Initialize()` method of the website plugin
> 
> Isnt the property readonly? Last time i checked it was.

I think the `href` field of the [URL interface](https://developer.mozilla.org/en-US/docs/Web/API/URL) was never readonly in any browser. Only a few fields, such as `origin` are marked as readonly, but `origin` is implicitly updated by setting `href`.

```javascript
const uri = new URL('http://a.a');
console.log('A:', uri.href);
uri.href = 'http://b.b';
console.log('B:', uri.href);
```

**Comment by MikeZeDev** [comment]
I was referring to our class field  URI, that is set as readonly. It cant be reaffected, but href can be changed. I am an idiot  😅 . Sorry about that
