### ISSUE TITLE
Add Nw.js install instructions to README.md

### ISSUE THREAD

**Issue by minhngoc25a** [manga-download/haruneko#195]
`nw` has to be in PATH in order for the software to successfully compile, otherwise it would fail. Although the README.md did mention that this one is based on NW.js, it is always a good practice to mention how to install NW.js in advance.

On Windows, `nw` can be installed by manually download the archive, extracting them and adding the directory to PATH, or we can do it automatically via package managers such as scoop:

```
scoop bucket add extras
scoop install extras/nwjs-sdk
```

On Mac, using Homebrew:

```
brew install --cask nwjs
```

On Linux, download the tar archive, extract them and add the directory containing the binary to PATH.

**Comment by Sheepux** [comment]
npm install is taking care of this, i never installed NWjs manually
