### ISSUE TITLE
Hardware Acceleration Toggle Option

### ISSUE THREAD

**Issue by solclearsky** [manga-download/haruneko#22]
On some machines, hardware acceleration will make apps look blurry or fuzzy. Adding a hardware acceleration toggle option in the settings would be great.

**Comment by ronny1982** [comment]
Have you tested one of the HaruNeko developer releases on such machines and can confirm they look blurry?

**Comment by Sheepux** [comment]
--disable-gpu or --force-cpu-draw  is available in nwjs, this could solve the issue.
As we didn't get a feedback, i'll close the issue.
