### ISSUE TITLE
ID Changed for bookmark importing

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/haruneko#248]
Reference issue for the bookmark importing feature

    '9anime': 'aniwave',
    'azoramanga': 'azoraworld',
    'apolltoons': 'mundomanhwa',
    'bacamangaorg': 'bacamanga',
    'bananascan': 'harmonyscan',
    'comicbushi': 'comicgrowl',
    'crazyscans': 'mangacultivator',
    'dalsei': 'viyafansub',
    'evascans': 'manwe',
    'firstkiss': 'likemanga',
    'flamescans-org': 'flamecomics',
    'gateanimemanga': 'gatemanga',
    'heavenmanga': 'beetoon', // (future zbulu PR)
    'heavenmanga2': 'heavenmanga', // (future zbulu PR)
    'kisscomic': 'readcomiconline',
    'kumascans': 'retsu',
    'lovehug': 'welovemanga',
    'lyrascans': 'quantumscans', //https://www.mangaupdates.com/groups.html?id=35005683580 'Formerly known as LyraScans'
    'mangamx': 'mangaoni',
    'manganel': 'manganato',
    'manganelos': 'mangapure',
    'mangaproz': 'mangapro',
    'mangaraw': 'mangagecko',
    'mangaswat': 'goldragon',
    'manhuaes': 'manhuaaz',
    'manhwaclub': 'manhwahentai',
    'muctau': 'bibimanga',
    'nitroscans': 'nitromanga',
    'nonbiri': 'comic21',
    'oxapk': 'manjanoon',
    'ozulscans': 'kingofmanga',
    'prismascans': 'demonsect',
    'randomscan': 'luratoon',
    'realmscans': 'rizzcomics',
    'reaperscansid': 'shinigamiid',
    'scansmangasxyz': 'scansmangasme',
    'secretscans': 'lynxscans',
    'shonenmagazine-pocket': 'shonenmagazine',
    'smangavfws': 'smangavf',
    'sushiscanfr': 'animesama',
    'vermanhwas': 'vermanhwa',
    'webtoontrcom': 'webtoontrnet',
    'yugenmangas': 'yugenmangas-es'

**Comment by ronny1982** [comment]
Current mappings will be introduced with the `BookmarkConverter` in #246 
Future changed of IDs need to be added to the `BookmarkConverter` and the corresponding test cases.

**Comment by MikeZeDev** [comment]
Ill keep this updated for references

**Comment by MikeZeDev** [comment]
This is no long maintained, better looking at the surce code.
