### ISSUE TITLE
mockup plugin selector

### ISSUE THREAD

**Issue by Sheepux** [manga-download/haruneko#3]
- [x] Dropdown
- [x] Advanced selection/filter
idea by @devemloop
![image](https://user-images.githubusercontent.com/19878135/99855453-33870c80-2b87-11eb-8153-35e1e03e47be.png)

**Comment by yoshiyes** [comment]
![image](https://user-images.githubusercontent.com/20050570/116631870-1d5f5280-a956-11eb-80dc-12cb49948672.png)
WIP
