### ISSUE TITLE
[UI Classic] Add Invisible line/border for resizing margins

### ISSUE THREAD

**Issue by zeoint** [manga-download/haruneko#313]
- If one wants to Resize the margins of media list and item list, one needs to go down to the resizer icon to do it.
- My suggestion / request is to add a hidden line at the end of scroll bar of each list.
- The user can grab the corner to resize the lists rather than holding the resize icon to resize the list.
- Example of the feature request can be seen in the image below.

---

![0](https://github.com/manga-download/haruneko/assets/127277950/5493d051-0bfa-4744-8376-25ab02877d0f)

**Comment by Sheepux** [comment]
Ultra low priority. The resize is here thanks to the css resize property. Adding border handlers is an extra work (not css native)

**Comment by Sheepux** [comment]
![image](https://github.com/user-attachments/assets/c5c0f608-da3d-496b-95d4-09b006f2c672)
Almost done, i still need to find a correct color/design.

**Comment by Sheepux** [comment]
completed by https://github.com/manga-download/haruneko/commit/0d4c2f800b7fe10ff3c87e875e5e2423b3f0e799
