### ISSUE TITLE
Download manager list on right side

### ISSUE THREAD

**Issue by zeoint** [manga-download/haruneko#314]
- Currently the download manager is very small.
- I request for the download manager to have its own list (Resizable) and be located on the right side of item list only when the content panel option is turned off in the settings.
- The same process as when the reader option is unchecked in hakuneko the manga and chpater list would expland, but here the download list.
- A preliminary example can be seen below.

---

![0](https://github.com/manga-download/haruneko/assets/127277950/a1f4920d-2a26-4c50-9f1d-457d1c01d967)

**Comment by Sheepux** [comment]
I was already working on it. It should be ready by the end of the week.

**Comment by Sheepux** [comment]
here is what i started working on:
![downloadprogress](https://github.com/manga-download/haruneko/assets/19878135/de496f0e-0583-4f93-887b-233738b20a7a)

This progress is a button that will open the DownloadTask manager. 

I have 3 UI options:

1. use a modal to open the download manager (easy)
2. add the download manager as a content (of the content pannel)
3. add an extra column before the content pannel

I'll go for 1 for now. Could be improved

**Comment by Sheepux** [comment]
Modal: a form of popup
https://carbon-components-svelte.onrender.com/components/Modal

**Comment by Sheepux** [comment]
> A couple suggestions,
> 
> * Green Tick and Green Color for progress after download completed = No error, Downloads completed. ( Example - Final Green tick and green color in the above gif).
> * Red Cross mark or exclamatory mark and red color for progress after download compoleted = Error, Download error / Missing pages, etc.

Already the case: https://carbon-components-svelte.onrender.com/components/ProgressBar#error-status

> Its subjective, but the two line download / progress bar in the above gif is confusing. Wouldn't it be better to add one of the below ones?
> 
> Title	Description
> **Single Line Progress Bar**	Like the one in hakuneko, it only has single bar which is sufficient (imo)
> **Numerical %**	Numerical % of the current chapter downloaded or total chapters downloaded
> **Downloaded Chapters / Total Chapters**	1 / 3 Chapters downloaded, 2 / 3 Chapters downloaded, and so on...
> **Downloaded Pages / Total Pages**	If multiple downloads, then show the downloading chapter pages only.
> **Example -** User is downloading 3 chapters and each chapter has 100 pages, then show chapter that is being download and pages being downloaded.
> 1 / 100, 2 / 100, so on.

I could introduce a "small version" of the download summary

**Comment by Sheepux** [comment]
First rework commited with a modal. I'll close this issue for now but it doesn't mean that it won't get improved later.
Let me know what you think. 

note: the engine doesn 't currently have the pause feature on tasks (will come later).
