### ISSUE TITLE
fuzzy search option

### ISSUE THREAD

**Issue by Robonau** [manga-download/haruneko#35]
cause of the multiple titles translations problem

so currently HN will not get 
`Tensei Kizoku no Isekai Boukenroku - Jichou wo Shiranai Kamigami no Shito`
if the site is 
`Tensei Kizoku no Isekai Boukenroku - Jichou o Shiranai Kamigami no Shito`
the only differance is the missing `w` but its a pretty common differance
fuzzy would deal with this quite handily
english example:
`She Professed Herself Pupil of the Wiseman`
`She Professed Herself the Pupil of the Wise Man`
and exact matches would still be at the top of the list, so its not gonna make it any worse

**Comment by sisco0** [comment]
Should https://github.com/krisk/Fuse be an affordable option for us?

**Comment by sisco0** [comment]
@Robonau take a look at the _PR_ video to get an idea of the implementation.

**Comment by Sheepux** [comment]
I truly wonder how it behaves on non ASCII languages

**Comment by manh21** [comment]
> I truly wonder how it behaves on non ASCII languages

Fuse doesn't support searching through non-ASCII characters. Explained in [this](https://github.com/krisk/Fuse/issues/133). 
The known workaround is to convert non ASCII to ASCII using [diacritics](diacritics)

**Comment by Sheepux** [comment]
I'm mostly thinking on asian characters as they are quite a big part of the connectors.

**Comment by sisco0** [comment]
Could you kindly provide a way to test this out? Hopefully something could be done under this issue for that @Sheepux .

**Comment by manh21** [comment]
@sisco0 you can find example data with asian characters in this [manga list](https://raw.githubusercontent.com/manga-download/hakuneko-cdn/master/manhuagui/mangas.json). More examples available at https://github.com/manga-download/hakuneko-cdn

**Comment by Sheepux** [comment]
> Could you kindly provide a way to test this out? Hopefully something could be done under this issue for that @Sheepux .

Actually i can't. That's something to be tested. Or probably there should be some kind of (automatic?) function to disable the fuzzy search (can be done in another PR).
You can find special chars in the sheep's manga unit-test connector

**Comment by sisco0** [comment]
After testing the `Sheep's Awesome Mangas` connector, I have two conclusions made up:
1. It seems that the search is working correctly when the same symbols are taken as input, even with missing symbols in-between. Evidence is attached at the end of this message.
2. The _Real 23_ example images are very funny, this was a really great surprise to find.

![image](https://user-images.githubusercontent.com/25695302/151721437-7401ce2f-f5e7-442d-99fd-16fd70fefc21.png)

**Comment by Sheepux** [comment]
So the feature seems quite good.
So what is left ? Chapter search ? Connector search ?
Do we need regexp search as we have multiple chapter selection available.

**Comment by Sheepux** [comment]
I'll close it for now. Fuzzy seems ok
