### ISSUE TITLE
resource busy or locked when relaunching NW.js in dev mode

### ISSUE THREAD

**Issue by manh21** [manga-download/haruneko#38]
### Step to repoduce:
- `git clone https://github.com/manga-download/haruneko.git`
- `cd haruneko`
- `npm install`
- `npm run serve:web-dev`
- `npm run launch:app-dev`
- close haruneko desktop client
- `npm run launch:app-dev` receive error message

### Known workaround
- Restart os

### Expected behavior
- Able to relaunch haruneko desktop client without restarting os

### Additional info
![image](https://user-images.githubusercontent.com/31276236/151107733-f1b74661-5ca6-49d0-8c2c-1fcfd5033495.png)
![image](https://user-images.githubusercontent.com/31276236/151107697-23850716-28b9-47a1-b255-2aa7b9144141.png)

### System Info
- OS: Windows 10 Build 19403
- Node Version: v17.4.0
- NPM Version: 8.3.1

**Comment by Sheepux** [comment]
make sure you don't run it with administrator priviledge first.

**Comment by manh21** [comment]
Are there any background jobs by chance? I just found that nw.js hasn't closed properly, it still has a background process that ate about 6GB of my ram

**Comment by Sheepux** [comment]
As a security measure, make sure to never run hakuneko with admin priviledge. If a connector has a flaw a malicious website could cause a mess (never happened).
The only time i had a background process was the splash screen still being hidden and didn't display the main window, but here you seem to be able to close the process by yourself, so ... no idea so far.

**Comment by Sheepux** [comment]
I can confirm that i get it as well.
Mostly when exiting from VScode (not from the app), hakuneko is closed but nwjs is still running in the process list.

NW is missing a terminating signal handler ?

**Comment by Sheepux** [comment]
Hasn't happened to me for a good while (was something fixed in NWjs ?).
I'll close the issue but will reopen if someone encounters it again.
