### ISSUE TITLE
Add an artificial-intelligence based solution for studying new connectors

### ISSUE THREAD

**Issue by sisco0** [manga-download/haruneko#39]
Creating and updating connectors are recurrent issues present in the hakuneko repository, as the community like to see their favourite sources integrated into the application.

A feasible first solution would base itself on a Github bot that runs a query over the given URLs (main portal, content list, content details, and content reader URLs) and compare styling, structure, and a overall score for each one of these pages against an already present cache for the set of connectors. These scores could be easily calculated by https://github.com/matiskay/html-similarity. Considering that we already have ground thruth connectors parent class this solution seems fair enough.

Further developments could base theirselves at integrating new pages directly at the client, giving our newcomer developer users the power to contribute to the haruneko codebase.

**Comment by Sheepux** [comment]
This issue should be in the hakuneko github, that's not haruneko specific. This github is temporary and will be fused into hakuneko once it's stable.

**Comment by sisco0** [comment]
> This issue should be in the hakuneko github, that's not haruneko specific. This github is temporary and will be fused into hakuneko once it's stable.

I agree, we must take care of considering mjs or ts connector files maybe.

**Comment by Sheepux** [comment]
Will close thins one in haru repo, feel free to create it on haku.
