### ISSUE TITLE
(Feature Request) Context menu options in items pane

### ISSUE THREAD

**Issue by zeoint** [manga-download/haruneko#444]
Please add some option on mouse right click in items pane,

1. Download All Available Chapters.
2. Download Selected Chapters.

**Comment by Sheepux** [comment]
It's planned as in classic ui i've implemented multi chapter selection for that (shift + ctrl)

**Comment by Sheepux** [comment]
Context menu commited last week

**Comment by Sheepux** [comment]
I don't think Ronny would add it to fluent core, it's more for dev/test related.
Is there something that makes you don't want to use the -classic- one ?
