### ISSUE TITLE
No Indicator chapters status in items pane

### ISSUE THREAD

**Issue by zeoint** [manga-download/haruneko#445]
There is no indication in items pane for chapters that are Not downloaded, Downloading, and Downloaded.

---

https://github.com/manga-download/haruneko/assets/127277950/da90d2a3-4841-4d70-9b27-7cc615ef4e85

**Comment by Sheepux** [comment]
because this is WIP :D Please don't open issues for things that were in hakuneko (would be too much issues). the plan is to port ISO
