### ISSUE TITLE
Image spacing in Viewer

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#471]
The decreased spacing is not fully decreased as there is still a small gap between the images.

![image](https://github.com/manga-download/haruneko/assets/95138799/e24b8d8e-d80c-4f3e-9981-e26b9a9696c0)

**Comment by Sheepux** [comment]
Yeah, i need to fix a lot of things in the viewer. Zooming is broken, magiScroll is not triggering correctly etc...

**Comment by Murshid7absi** [comment]
> Yeah, i need to fix a lot of things in the viewer. Zooming is broken, magiScroll is not triggering correctly etc...

Thanks guys. Keep up the good work!🤜🏻🤛🏻
I'm on my coding journey. I hope I can help later on with the issues
