### ISSUE TITLE
Additional Tag for Chapter Title Format Variables

### ISSUE THREAD

**Issue by nexist418** [manga-download/haruneko#48]
Since the Rename string is applied to both the view and the file name, it would be convenient to add a language tag. Multi-language sites have their files all renamed to the same name despite one being English, one being Russian, etc. (especially obvious on MangaDex).

A simple tag to indicate the language (even if just the two-letter code EN, ES, RU, IT, etc.) would be great.

**Comment by Sheepux** [comment]
TR to haku https://github.com/manga-download/hakuneko/issues/4809
