### ISSUE TITLE
[NWjs] Window drag no longer working

### ISSUE THREAD

**Issue by Sheepux** [manga-download/haruneko#480]
Following nwjs ugprade
https://github.com/manga-download/haruneko/commit/799f02bd51cf4b059675575abe053dec84496102

Drag and drop is not working. Issue on NWjs : 
https://github.com/nwjs/nw.js/issues/8153

**Comment by MikeZeDev** [comment]
Are we using D&D in the firs tplace?

**Comment by Sheepux** [comment]
I would not create an issue if that wasn't the case.
It's what handling the frameless drag on top. You cannot move the window anymore.

**Comment by Sheepux** [comment]
fixed by nw 0.85 (not released yet)

**Comment by Sheepux** [comment]
reopening as the issue is not fixed on nw side (npm update overwrote the unreleased fix 0.85)

**Comment by Sheepux** [comment]
solved with nw 0.90
