### ISSUE TITLE
Problem connecting to sites

### ISSUE THREAD

**Issue by Mahora2106** [manga-download/haruneko#482]
Hello, I managed to install the application, but I cannot connect to the sites with my accounts.
When I do, open website URL, nothing happens.
Is this normal?
I thank you in advance.

![image](https://github.com/manga-download/haruneko/assets/71670560/da810dc1-4e02-4cf7-9f2f-cf8bc57310a4)

**Comment by MikeZeDev** [comment]
Ahem.

"Not coded yet" :D

**Comment by MikeZeDev** [comment]
Closed "not coded yet"

**Comment by Mahora2106** [comment]
So for the moment, I can't yet retrieve the series with my email account?

**Comment by MikeZeDev** [comment]
Wait for the fix i mentioned to be "MERGED", and either you redownload Haruneko, either you update it using git but i guess its too complicated for the end user :D

**Comment by Sheepux** [comment]
Browse website button is now working ;)
I also removed the "test plugin" button, those were just UI test.

**Comment by Mahora2106** [comment]
Great, it works. Thank you so much
