### ISSUE TITLE
application is not opening on linux mint

### ISSUE THREAD

**Issue by underailton** [manga-download/haruneko#514]
The app is not opening on linux mint, flatpak and system package. 

Shows this message when I try to open it in the terminal: 
[3675:0226/120014.277356:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap 

System:
  Kernel: 5.15.0-97-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASRock model: 760GM-HD serial: <superuser required>
    BIOS: American Megatrends v: P1.00 date: 06/11/2019
CPU:
  Info: quad core model: AMD FX-4100 bits: 64 type: MT MCP arch: Bulldozer rev: 2 cache:
    L1: 192 KiB L2: 4 MiB L3: 8 MiB
  Speed (MHz): avg: 1721 high: 2151 min/max: 1400/3600 boost: enabled cores: 1: 2151 2: 1935
    3: 1402 4: 1398 bogomips: 28738
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GF119 [GeForce GT 610] vendor: Micro-Star MSI driver: nvidia v: 390.157 pcie:
    speed: 2.5 GT/s lanes: 16 bus-ID: 01:00.0 chip-ID: 10de:104a
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 92
  Monitor-1: HDMI-0 res: 1920x1080 dpi: 93 diag: 604mm (23.8")
  OpenGL: renderer: GeForce GT 610/PCIe/SSE2 v: 4.6.0 NVIDIA 390.157 direct render: Yes
Audio:
  Device-1: AMD SBx00 Azalia vendor: ASRock driver: snd_hda_intel v: kernel bus-ID: 00:14.2
    chip-ID: 1002:4383
  Device-2: NVIDIA GF119 HDMI Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel pcie:
    speed: 5 GT/s lanes: 16 bus-ID: 01:00.1 chip-ID: 10de:0e08
  Sound Server-1: ALSA v: k5.15.0-97-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes

**Comment by Sheepux** [comment]
Same issue that we had in hakuneko ? Wtf with those linux distributions ?
Try to add --disable-gpu-compositing
in the launch:dev script https://github.com/manga-download/haruneko/blob/master/app/nw/package.json#L29

**Comment by MikeZeDev** [comment]
Does that flags helped?

**Comment by MikeZeDev** [comment]
Its command line arguments.

**Comment by underailton** [comment]
Sorry for the delay, I tried to run it in the terminal and it shows this error.

username:~$ flatpak run --branch=stable --arch=x86_64 --command=hakuneko --file-forwarding io.github.hakuneko.HakuNeko @@u %U @@
Gtk-Message: 20:59:59.950: Failed to load module "xapp-gtk3-module"

Usage:
  /app/lib/hakuneko-desktop/hakuneko [OPTIONS]

Options:
  -u, --update-url=<URL>      URL to be checked for web-application updates
                              Default: "http://manga-download.github.io/hakuneko/{version}/latest"
  --startup-url=<URL>         URL to the entrypoint of the web-application
                              Default: "hakuneko://cache/index.html"
  -c, --cache-directory=<DIR> Directory where the web-application is stored
                              Default: system's default
  --user-directory=<DIR>      Directory where user settings are stored
                              Default: system's default


--------------
Framework Info
--------------
Electron : 6.1.7
Chrome   : 76.0.3809.146
Node     : 12.4.0


-------------
Configuration
-------------
Update URL           : https://manga-download.github.io/hakuneko/6.1.7/latest
Connector Protocol   : connector
Application Protocol : hakuneko
Startup URL          : hakuneko://cache/index.html
AppCache Directory   : /home/ailton/.var/app/io.github.hakuneko.HakuNeko/cache/hakuneko-desktop
UserData Directory   : /home/ailton/.var/app/io.github.hakuneko.HakuNeko/config/hakuneko-desktop

Fontconfig warning: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 5: unknown element "reset-dirs"
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 6: invalid attribute 'salt'
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 7: invalid attribute 'salt'
Fontconfig warning: "/run/host/font-dirs.xml", line 4: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 4: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 5: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 5: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 6: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 6: invalid attribute 'as-path'
Fontconfig error: Cannot load config file from /run/host/font-dirs.xml
*** stack smashing detected ***: terminated
*** stack smashing detected ***: terminated
*** stack smashing detected ***: terminated
[2:0419/210004.078937:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.

**Comment by MikeZeDev** [comment]
IIRC flatpak is made by a third party so youd better ask them for the font errors.
'The display compositor is frequently crashing" is an Electron bug and there is little to nothing we can do. Updating it is a pain so we are developing Haruneko from scratch.

There was something in the FAQ or other tickets about a command line argument you could have used.

1) try nightly because electron version is slightly more recent
2) https://hakuneko.download/docs/troubleshoot/  try the --disable-gpu switch ?

**Comment by ronny1982** [comment]
Wrong project, this is about HaruNeko, but the console output shows HakuNeko Stable
see: https://github.com/manga-download/hakuneko/issues/6826
=> Closed

**Comment by underailton** [comment]
Hello, based on this explanation I was able to run and open the program without problems, I just changed a few lines in the command, it was like this “hakuneko-desktop start:dev”: “electron . --no-sandbox” in the version packaged in .deb
