### ISSUE TITLE
(Site request) comicfans

### ISSUE THREAD

**Issue by xeolod** [manga-download/haruneko#539]
Site - https://bilibilicomics.net/
Chapter - https://bilibilicomics.net/comic/2207-a-record-of-a-mortal-s-journey-to-immortality
Chapter Viewer - https://bilibilicomics.net/episode/6511-preview

**Comment by MikeZeDev** [comment]
No need to request here for now, as i look for requested websites in Hakuneko issues list. Somme have the "Haruneko" tag.

https://github.com/manga-download/hakuneko/issues/6876
