### ISSUE TITLE
Sending Referer by default in requests

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/haruneko#56]
* Since its a given that we have to mimic browser behavior in order not to trigger server errors and Cloudflare, make sure all requests sends at least the website url as referer by default.

* Having the possibility to override this for "pages" without having to overload a function (ie. using the plugin requests options when downloading pages)

**Comment by ronny1982** [comment]
The default extension/decorator already does this.

Each website can add various information such as headers, tokens or encryption keys to the `Parameters` property of a `Page`, but as a result each website musst implement the `FetchImage` method to process the additional information that it has set on the `Page`.
