### ISSUE TITLE
Manual updating of source URL

### ISSUE THREAD

**Issue by thenetlogs** [manga-download/haruneko#565]
It seems that some sources are currently active again with the new URL, so some sort of option to edit the source URL would give users without coding knowledge an option to make source working and viable

**Comment by thenetlogs** [comment]
ZinManga for example have a new working website, so a simple URL swap would make it work again I think

**Comment by MikeZeDev** [comment]
An option is planned to let the user manually change the URL but only for website that often change url, as a per website setting.

If users can change the url themselves for EVERY WEBSITES it would prevent us developers & users to know the website url changed . And that quite the problem in the long term. 

If no one complain, we dont know about most websites. In the end we may end up having too many "fake dead" websites like that.
In fact, its already the case for Hakuneko. People just take websites for dead when they just changed url.

I am rather against this idea.

**Comment by MikeZeDev** [comment]
There is also the question : "user has set a custom url, Update push a new url that works. What should we do? "

**Comment by thenetlogs** [comment]
How would you decide which website is URL-changeable and which is not? What is a minimum URL change frequency to allow that option? Once a month? Once in 6 month? Would you need to put some argument in connector for allowing URL change?

How would not allowing users to change URL locally help with "dead" websites? My point is that if I know it's not dead and know new URL I can change it and continue to use it in Hakuneko

**Comment by thenetlogs** [comment]
Update URL takes priority if it works

**Comment by Sheepux** [comment]
> How would you decide which website is URL-changeable and which is not?

It's all about the amount of issues created that are about the same website. Usually when we get an issue every month on the same connector because trhey changed the domain again then we plan for custom URL change.
But i agree with MrLapin, for "not so changing" connectors, if people change on their side we wouldn't be aware of the incorrect
value.

> How would not allowing users to change URL locally help with "dead" websites? My point is that if I know it's not dead and know new URL I can change it and continue to use it in Hakuneko
when it's just domain change it's usually fixed within the same day once reported (not currently as we're working on haru more than maintaining connectors)

**Comment by MikeZeDev** [comment]
Moreover, i'd say perhaps for a rough 45% of the time an url change there is something else that changed and need to be fixed.

**Comment by MikeZeDev** [comment]
Closed , as its a per website change, and decision is up to maintainers/devs
