### ISSUE TITLE
Having the possibility to store custom properties for a manga/chapter

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/haruneko#57]
Use cases  : On some websites you have to mix different methods for fetching infos : using urls, their own api, etc..

I.e  you have to chose an identifier for each manga : sometimes an internal id (for their api or not) sometimes a pathname.
And sometimes you need both or various reasons. The information is lost between "getmangas, getchapters and getpages" procedures

Storing it inside as class variable (In Plugin/Connector) is not a good idea as its a per-item thing and we can, for example, update manga list while downloading pages. I cant name a particular manga or website but it happened when i was working on connectors.

**Comment by ronny1982** [comment]
Each instance has its very own `Identifier` property. It is used to identify a single resource/state. An identifier can be any string serializable structure, e.g. a value object which can be serializes as JSON and then stored in the ` Identifier`.
A parent's `Identifier` can be accessed at any time via `Parent.Identifier`.

If this is not sufficient, a specific use-case is required for further investigation.

**Comment by MikeZeDev** [comment]
That should pretty much cover it. I am closing this. Thanks
