### ISSUE TITLE
[Future Idea] Download the chapters without excessive cuts made by the Web or Company where it is extracted.

### ISSUE THREAD

**Issue by CloudBladed** [manga-download/haruneko#61]
Allow downloading joined JPG sheets, I mean, there are Webtoon companies that have sheets divided into many pieces in each chapter, which makes it difficult to read and sequence the image.

The problem is already reflected when downloading in Epub. cbz or PDF. Where the image cannot be appreciated well due to the cuts.

_**So, it's like I know in any format.**_
![image](https://user-images.githubusercontent.com/70826672/211163763-bcbbc45a-6bbf-4fad-8c68-e4f0e26089aa.png)

And this is how I would like it to be seen in any format that allows its download, JPG being optimal.
![image](https://user-images.githubusercontent.com/70826672/211163808-d803c853-54b6-40c9-ab9b-6227b0330849.png)

_**### Make sure that the final result does not compress or resize the image so as not to lose quality.**_

**Comment by Sheepux** [comment]
Content is provided as the website is providing it.
It's all about the reader/viewer you're using. Hakuneko's reader is able to remove image spacing when viewing.
Don't use PDF for webtoons, pdf are page based and not meant for images without cuts.
A Feature could be to merge all images into a single one. I'm not sure about the use case (it's too specific to the reader tool)
