### ISSUE TITLE
Downloaded chapters still show download icon

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/haruneko#618]
![Capture1](https://github.com/manga-download/haruneko/assets/51503984/046b455e-f233-4ef9-a23e-7cd3a6dc1782)
![Capture2](https://github.com/manga-download/haruneko/assets/51503984/416a58ac-0a7a-4013-b92f-3f6a3a661216)

When restarting the app after downloading a chapter the folder icon reverts back to download icon.

**Comment by MikeZeDev** [comment]
I guess its "not coded yet"?

**Comment by Sheepux** [comment]
Yup, not coded yet

**Comment by Sheepux** [comment]
Closing as to track actual "issues" and not "things pending"
