### ISSUE TITLE
PiccomaFR : api change and race condition? 

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/haruneko#626]
They changed the place where to get image list. Its not pdata.img but pdata.contents. Structure stays the same.

The thing is, the promise keep failing with "intermediate value " errors in Haruneko, while it works fine in my browser.

**Comment by ronny1982** [comment]
May check the production code in debugger for anomalies, since this function is transformed by _Vite_ during the build.

**Comment by MikeZeDev** [comment]
Site closed
