### ISSUE TITLE
Enhancement Idea: Alphabetical Seperators

### ISSUE THREAD

**Issue by forestpas3** [manga-download/haruneko#635]
**Is your feature request related to a problem? Please describe.**
Just a visual help to find faster the manga you bookmarked (like the color code in dictionaries) 

**Describe the solution you'd like**
A extension that would automatically add empty bookmarks as alphabetical separators. (See image)
Why a extension ? Because not everyone needs the latin alphabets (eg: if the manga has a japanese title it wouldn't be usefull). But maybe there could be a extension for the japanese language, etc.

**Describe alternatives you've considered**
DIY, it's pretty easy to modify the bookmark file, so maybe just a premade code (for copy-paste) and an official tutorial on how to add it manually.

![image](https://github.com/manga-download/haruneko/assets/23244934/7b6c850d-2ab4-401f-8100-b07c5feef0aa)

**Comment by MikeZeDev** [comment]
How do do you suggest it works with chinese, japanese, thai, arabic whatever manga ?

**Comment by Sheepux** [comment]
please, create this request on hakuneko's github as it won't be done in haru until it's merged back into haku
