### ISSUE TITLE
Some manga of to-ti isn't downloadable

### ISSUE THREAD

**Issue by NNguyenHoangDang** [manga-download/haruneko#643]
Some manga of to-ti isn't downloadable
Examples: 
https://to-ti.in/product/yasegaman
https://to-ti.in/product/mameshika

**Comment by MikeZeDev** [comment]
What about describing whats going on? :D

**Comment by NNguyenHoangDang** [comment]
I get this error:
Failed to fetch
TypeError: Failed to fetch
    at NodeWebkitFetchProvider.Fetch (https://haruneko.pages.dev/LX3CB9C6/DownloadTask.js:12:15969)
    at async DeferredTask.action (https://haruneko.pages.dev/LX3CB9C6/HakuNeko.js:1:22430)
    at async DeferredTask.Run (https://haruneko.pages.dev/LX3CB9C6/DownloadTask.js:12:28037)
    at async B.Run (https://haruneko.pages.dev/LX3CB9C6/InteractiveFileContentProvider.js:1:1532)

**Comment by NNguyenHoangDang** [comment]
<img width="960" alt="Screenshot 2024-06-11 114433" src="https://github.com/manga-download/haruneko/assets/125973917/dd7a04d5-4b4f-4c94-b822-ae5853359f76">

**Comment by Sheepux** [comment]
Tested and it works fine :\
I guess this error means there was an issue while trying to download (connectivity error ?)
Try to open the console F12 and check the network tab

**Comment by NNguyenHoangDang** [comment]
<img width="945" alt="image" src="https://github.com/manga-download/haruneko/assets/125973917/16a70c91-ab81-4209-a83c-6bf885d191ad">

**Comment by Sheepux** [comment]
Blocked mixed-content ? Do you have some kind of proxy/antivirus that would block the response ?
If not Can you click on a red line and fine the heaer response as well as the response content

**Comment by NNguyenHoangDang** [comment]
<img width="959" alt="image" src="https://github.com/manga-download/haruneko/assets/125973917/5a5d212f-f76b-41ba-9ed7-a7649f375c45">

**Comment by MikeZeDev** [comment]
Why do i see "hakuneko.pages.dev"?

**Comment by Sheepux** [comment]
Reopening: Haruneko.pages.dev is when you use "nightly" version. 
The issue here is an http request from an https page (the nightly page). It's an issue that needs fixing.

**Comment by MikeZeDev** [comment]
How come its not occurring while developing? Why dont we have mixed content errors?

**Comment by Sheepux** [comment]
when we develop we use localhost http, when the user starts the release binary it gets fetched from haruneko./pages.dev but with https leading to mixed content issue

**Comment by MikeZeDev** [comment]
So its just a problem affecting release binary? I am puzzled.

**Comment by MikeZeDev** [comment]
Ooooh those image are affected by the Photon Deproxying bug too, its the same bug indeed !
