### ISSUE TITLE
Updating MangaReader.to returns $e

### ISSUE THREAD

**Issue by pjft** [manga-download/haruneko#644]
Hi. Thanks for the great project here! 

I was trying to refresh the MangaReader.to connector, but when I do so it just returns $e. 

From what I can gather from the Inspect window and network tab, it doesn't even seem to start a network request?

The Console shows:

```
MangaPlugin.ts:60 Uncaught (in promise) $e
    at $_e.FetchMangas (http://localhost:5000/LXBM0MYL/InteractiveFileContentProvider.js:1:3001)
    at v.Update (http://localhost:5000/LXBM0MYL/InteractiveFileContentProvider.js:1:4030)
    at async HTMLButtonElement.E (http://localhost:5000/LXBM0MYL/FrontendClassic.js:39:9132)
```

Unsure what else to share, but happy to do things on my end to troubleshoot further.

Thanks.

**Comment by antoine-sncf** [comment]
Strange, try to define in the settings the download directory. 
As the error message states InteractiveFileContentProvider i'm gessing he's waiting for you to give a folder (it should have been interactif). I'll test this evening

**Comment by pjft** [comment]
Thanks. I have defined a download directory in the settings, as I have downloaded some chapters successfully from other sources, but I'll try it later and report back. Sorry for the trouble.

**Comment by MikeZeDev** [comment]
It has not been coded........

**Comment by pjft** [comment]
Ah :) That explains it then. Thanks!

**Comment by Sheepux** [comment]
Shouldn't non implemented website  throw an error  such as ` "not imported from hakuneko yet" ?`

**Comment by MikeZeDev** [comment]
Legacy connectors dont have implemented methods, so an error "Not implemented" is thrown. when you try do do anything.
I dont understand either.

**Comment by Sheepux** [comment]
Just tried and I get an NotImplementedError as expected

Uncaught (in promise) NotImplementedError
    at default.FetchMangas (MangaPlugin.ts:60:15)
    at MangaPlugin.Update (MangaPlugin.ts:127:44)
