### ISSUE TITLE
Add new settings for using flaresolverr

### ISSUE THREAD

**Issue by Tsuna77** [manga-download/haruneko#669]
Flaresolverr project is a cloudflare automatic bypasser.

With flaresolver you can ask for a session that you can use for your scripts.

It's an API and not a proxy, so it's need a specific developement. but can (if the user have it installed) allow to automaticly bypass cloudflare without asking to manualy update challenge cookies.

**Comment by ronny1982** [comment]
There is [HakuNeko Assistant](https://haruneko-docs.pages.dev/user-manual/usage/fluent-core/tutorials.html#bypass-cloudflare) which already does the job.
