### ISSUE TITLE
Question: Minimal requirement on MacOs

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/haruneko#686]
Hello
It's not a issue but I'm looking for the minimum requirement on MacOs

Does it need Google Chrome installed (for example)?

Today, It runs only on website without cloudflare like hakuneko on my configuration (Safari + Firefox).

**Comment by Sheepux** [comment]
There is no requirement, haruneko is including it's own chrome version just like haku did.

Cloudflare is working through <haruneko's assistant> https://github.com/manga-download/haruneko-assistant
The plugin is currently only for chrome/edge
https://github.com/manga-download/haruneko-assistant/blob/master/docs/Connect%20with%20HakuNeko.md
