### ISSUE TITLE
Alphapolis: Manga's folder name not save correctly

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/haruneko#689]
When download some manga from Alphapolis on Haruneko, Manga's folder name not save name correctly

example: 
``狙って追放された創聖魔法使いは異世界を謳歌する`` (https://www.alphapolis.co.jp/manga/official/573000610) Haruneko will save as ``狙って追放された創聖魔法使いは異世`` or ``工芸職人《クラフトマン》はセカンドライフを謳歌する`` (https://www.alphapolis.co.jp/manga/official/908000587) will save as ``工芸職人《クラフトマン》はセカンド``.

**Comment by MikeZeDev** [comment]
Tried with https://www.alphapolis.co.jp/manga/official/573000610.

Title is for some reasons saved as "狙って追放された創聖魔法使いは異世" (plus 3 dots but Gitbhub dont let me post the message, meaning there are incorrect characters somewhere . Thats weird.

**Comment by MikeZeDev** [comment]
Perhaps we could "FILTER FROM THE LIST MANGAS ENDING WITH ..." then you can use clipboard for them? 💡
