### ISSUE TITLE
 Website Suggestion | https://mangagalaxy.org 

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#709]
New websites:
https://mangagalaxy.org/home
https://mangagalaxy.org/series
https://mangagalaxy.org/series/hardcore-leveling-warrior
https://mangagalaxy.org/series/hardcore-leveling-warrior/chapter-212

**Comment by MikeZeDev** [comment]
No need to request it HERE if its already requested here https://github.com/manga-download/haruneko/issues/643
