### ISSUE TITLE
Website Suggestion | https://stonescape.xyz/

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#710]
New Website:
https://stonescape.xyz/
https://stonescape.xyz/series/
https://stonescape.xyz/series/nakanglim/
https://stonescape.xyz/series/nakanglim/ch-27/

**Comment by MikeZeDev** [comment]
MAdara

**Comment by Sheepux** [comment]
Please open website request in hakuneko's github (not here, we don't want to flood the issues)
