### ISSUE TITLE
Line Webtoons (English) is not added

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#711]
Line Webtoons (English) is not added:
https://www.webtoons.com/en/

![image](https://github.com/user-attachments/assets/66f6f5df-ce6c-4004-b2de-d481590e41b6)

**Comment by MikeZeDev** [comment]
Useless issue.  Being available in the menu doesnt mean its coded, there are many placeholders. Haruneko is a WIP¨program.
