### ISSUE TITLE
NW GUI Not display !

### ISSUE THREAD

**Issue by Lordsneak** [manga-download/haruneko#712]
Hi, my system is Windows 10 and I have problem when I run my app with " npm run launch:dev --workspace app/nw " ,nw gui not display and still in background run !! 
This is image : 
<img width="960" alt="PROBLEM" src="https://github.com/user-attachments/assets/c0f44d10-11dc-4b55-947c-90b4e8b02824">

I try, npm run launch:dev --workspace app/electron
<img width="960" alt="elec" src="https://github.com/user-attachments/assets/7b8784fa-9ed1-445a-8d43-02307866cb31">

and npm run serve:dev --workspace web, but not working !
<img width="960" alt="web" src="https://github.com/user-attachments/assets/0e318f31-3d78-496a-aa4d-eeb0430acb7e">

same problem in Windows 11

**Comment by ronny1982** [comment]
Have you followed the [documentation](https://haruneko-docs.pages.dev/development-guide/setup-environment.html#development-mode)?
Is the web-app really running before you start NW or electron?

**Comment by MikeZeDev** [comment]
Its not meant to be opened in Chrome. Read the doc. You launch the server, then the client app.

**Comment by Lordsneak** [comment]
Thanks its work !
