### ISSUE TITLE
Add a feature whether the folder exists or not in Bookmark

### ISSUE THREAD

**Issue by Lordsneak** [manga-download/haruneko#715]
Hi, I am downloading the manga to my computer through haruneko and I don't know if the manga I am downloading is on my computer or not without checking. The important thing is, is it possible to add a feature that shows if a folder exists and has been downloaded, as in the hakuneko version?. Like => 
![bookmark](https://github.com/user-attachments/assets/bd2ec12a-863c-4719-aad4-d3f7cabdd2ec)

**Comment by Sheepux** [comment]
do not create issues for existing features in haku, they'll be ported
