### ISSUE TITLE
[GANMA] Problem in Some Manga Series

### ISSUE THREAD

**Issue by DragonWira** [manga-download/haruneko#718]
In the media list, I opened one of the official websites and several titles had the words TypeError: Cannot read properties of undefined (reading 'items') Cannot read properties of undefined (reading 'items') in the items list section, is this really not possible or is there something that needs to be set?
![Screenshot 2024-07-30 200809](https://github.com/user-attachments/assets/aeb02d3a-e790-42e0-bd00-2a055de52048)

**Comment by MikeZeDev** [comment]
The problem il will have to diagnose this is : If that is only one some manga, there is no way i can easily find the manga in the list.
Will all due respect, japanese is gibberish to me.

Could you please post the manga link? 😔

**Comment by MikeZeDev** [comment]
They probably changed something

**Comment by MikeZeDev** [comment]
Can you even access this manga on the website? 

Lets say you have this one : h--ps://ganma.jp/1f7467e0-da82-4981-8bd5-436c83e4ff3e.
Manga ID is 1f7467e0-da82-4981-8bd5-436c83e4ff3e.  Website correctly return a list of chapters.

From mangalist i got this manga id : fa9a96a0-f0b6-11e9-b366-0ebdbc8f6976

 h--s://ganma.jp/fa9a96a0-f0b6-11e9-b366-0ebdbc8f6976 is a "not fund manga" page on the website.
