### ISSUE TITLE
Incorrect Release Naming for Haruneko

### ISSUE THREAD

**Issue by abhishek-exists** [manga-download/haruneko#726]
Hi @MikeZeDev ,

I encountered an issue while trying to download a [pre-release](https://github.com/manga-download/haruneko/releases) version of `Haruneko`. It seems that all the releases, except for the oldest one, incorrectly mention `Hakuneko` instead of `Haruneko`.

This appears to be a mistake. Could you please clarify why `Hakuneko` releases are being listed under `Haruneko`?

CC: @ronny1982

**Comment by Sheepux** [comment]
Haruneko IS hakuneko, it's just a codename for v10

**Comment by MikeZeDev** [comment]
Ho do i disable mentions already ? 😴
