### ISSUE TITLE
[UI Classic] Tooltip Display Issue

### ISSUE THREAD

**Issue by abhishek-exists** [manga-download/haruneko#727]
Hi Team,

I have noticed a problem with the the tooltips not displaying correctly in mac-os; they are being obscured by adjacent sections. This issue occurs specifically in the `Updates` and `Languages` button sections.

**Suggestion**: As a temporary solution, we could consider moving the tooltip position from the `top` and `bottom` to the `left` and `right` for these cases. I have attached a screenshot to illustrate the issue.

Let me know your thoughts on this suggestion or if you have a better solution in mind!

**Current behaviour**:
<img width="672" alt="image" src="https://github.com/user-attachments/assets/ff54ec82-463d-4551-b710-94e590d2b3c3">

**After fixing**:
<img width="638" alt="image" src="https://github.com/user-attachments/assets/cf43d3c2-c7e5-4d38-a201-0cc1f383018a">

CC: @Sheepux

**Comment by MikeZeDev** [comment]
Thanks for reporting 👍 , just please dont mention people we check issues you know 🤦

**Comment by Sheepux** [comment]
issue appeared when overflow-y was added so that resizable can be used.
Proposed solution: remove html resizable and manage it with a custom JS script

**Comment by Sheepux** [comment]
Fixed by https://github.com/manga-download/haruneko/commit/0d4c2f800b7fe10ff3c87e875e5e2423b3f0e799
Added custom resizebar, removed css resize & overflow-y
