### ISSUE TITLE
[UI Classic] Plugin Search Click Event Not Functioning

### ISSUE THREAD

**Issue by abhishek-exists** [manga-download/haruneko#728]
Hi Team,

I've encountered an issue where the plugin search does not work correctly when a plugin field is already selected. Here are the 
steps to reproduce the problem:
1. Ensure you have a plugin already selected.
2. Search for a plugin that is not currently selected.
3. Attempt to select the new plugin using a mouse click.

**Note**: The selection works if you navigate using the arrow keys and then press Enter/Return. Additionally, it functions correctly when you clear the current selection before searching for and clicking on a new plugin.

**Current Behavior**:
The searched plugin does not get selected when clicked.

**Expected Behavior**:
The plugin should be selected normally upon clicking.

I have attached a video for reference.

https://github.com/user-attachments/assets/9a04eabf-266e-4306-8c1d-b23191dc3d45

Let me know what you think would be a better solution to address this issue!

CC: @Sheepux

**Comment by Sheepux** [comment]
They probably broke it in a recent update

**Comment by MikeZeDev** [comment]
That what i was mentioning on discord, thanks for making an issue.

**Comment by Sheepux** [comment]
First investigations: using arrow and enter works. when using click the event is not dispatched at all. I don't know why yet. Possiblity a DOM layer issue ?
