### ISSUE TITLE
Option for Sorting Mangas [UI Classic/Fluent Core]

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#732]
Make a function to sort manga with certain options like A-Z, Z-A, Most Rated, Most Recent, ..., etc.

**Comment by Sheepux** [comment]
Alphabetical, could be

Most rated: no (not something we fetch)
Moste recent: no (not something we fetch)

**Comment by Sheepux** [comment]
Create this issue in hakuneko's i'll add it to the https://github.com/manga-download/haruneko/issues/40 (we don't want features requests to flood this git)
