### ISSUE TITLE
Referer issues

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/haruneko#74]
1) Requests are sent with default referer aka http://localhost:3000 

Default behavior should be at least sending truncated uri from the request itself.

2) I cant seems to use a custom referer.

Ex : CartoonMad : Chapter list is https://www.cartoonmad.com/comic/1152.html.
To fetch one chapter html page i need to send the chapter list url as referer. Which i cant.

**Comment by ronny1982** [comment]
Good catch, seems this got forgotten in some commented prototype code
