### ISSUE TITLE
Bomtoon 'puzzled' scans

### ISSUE THREAD

**Issue by Monikaa09** [manga-download/haruneko#761]
Bomtoon has implemented a kind of new protection. For example Low Tide in Twilight panels are puzzled like this and I can't see/read the chapter on Haruneko. 

![image](https://github.com/user-attachments/assets/fefb5af4-948b-4644-81f1-a4e72da590cb)

**Comment by MikeZeDev** [comment]
Since i have trouble reading non latin languages, can you please give the manga link ?

**Comment by Monikaa09** [comment]
> Since i have trouble reading non latin languages, can you please give the manga link ?

It's this one: https://www.bomtoon.com/detail/night_of_W

**Comment by MikeZeDev** [comment]
> > Since i have trouble reading non latin languages, can you please give the manga link ?
> 
> It's this one: https://www.bomtoon.com/detail/night_of_W

Thanks.

And ofc i have to be logged for this >_>
