### ISSUE TITLE
shonenjumpplus missing /magazine support

### ISSUE THREAD

**Issue by Robonau** [manga-download/haruneko#768]
https://github.com/manga-download/hakuneko/blob/62c5099c0558e540873d0ad036bf38ebd679c869/src/web/mjs/connectors/ShonenJumpPlus.mjs#L14

https://github.com/manga-download/haruneko/blob/9066dda231ce08cdde4dfabfdf0835e09ae93a2d/web/src/engine/websites/ShonenJumpPlus.ts#L8

**Comment by MikeZeDev** [comment]
nice catch

**Comment by MikeZeDev** [comment]
Closed https://github.com/manga-download/haruneko/commit/983505b532844f76342d09c2a4971893efb36b77
