### ISSUE TITLE
Mgeko.cc not working

### ISSUE THREAD

**Issue by Zoroam** [manga-download/haruneko#774]
https://www.mgeko.cc/ connector isn't working. They've enabled under attack mod on cloudflare and comics aren't loading on app after that,

**Comment by ronny1982** [comment]
See: https://haruneko-docs.pages.dev/user-manual/usage/fluent-core/tutorials.html#bypass-cloudflare

**Comment by MikeZeDev** [comment]
I have no cloudflare on my end for this website

**Comment by Zoroam** [comment]
Issue is fixed

**Comment by MikeZeDev** [comment]
Its not. We need to fix manga list updating :)
