### ISSUE TITLE
WeebCentral Doubled Chapter Pages

### ISSUE THREAD

**Issue by Loomynarty** [manga-download/haruneko#787]
Hello! I noticed that WeebCentral is downloading chapter pages two times over.  I have pinpointed where the problem is below.

![electron_2EmjfXLYKg](https://github.com/user-attachments/assets/5ba621ad-961c-42e3-91ba-b0eb28e68238)

In my local environment, replacing the CSS filter `main section img[alt*="Page"]` to `main section img[alt*="Page"]:not([x-show])` has successfully fixed this issue.

**Comment by MikeZeDev** [comment]
I think they are making changes juste to mess with us

**Comment by MikeZeDev** [comment]
Closed with #eca3784f6cc9c6da4aa2f4c2f21390298196d106
