### ISSUE TITLE
Daycomics: Comics hidden behind initial purchase not showing

### ISSUE THREAD

**Issue by erictbar** [manga-download/haruneko#800]
Under Daycomics [FAQ](https://daycomics.com/help/faq):
> Some comics are not showing.
> Due to the current change in an external advertisement policy, some series can only be seen once you
purhcase coins or become a member. Every hidden series will be open within 48 hours of your first
purchase time.

I am seeing that series under this policy, of which I have purchased chapters from two series, are not able to be pasted into Haruneko. While the one series that is publicly shown is working.

Series that copies and allows me to download purchased chapters (**NSFW LINKS**):
https://daycomics.com/content/102637

Series that do not show up in Haruneko:
https://daycomics.com/content/103048 (Girls in Prison)
https://daycomics.com/content/100899 (Punishing My Pet Slave Elf)

**Comment by MikeZeDev** [comment]
The series you mentioned gives error 500 when pasting. I dont see any thing that can change that.
