### ISSUE TITLE
Corocoro: Website change

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/haruneko#801]
Shogakukan renewal Corocoro's online manga site, manga list and reader has bean change from CoreView.

site: https://www.corocoro.jp/
list: https://www.corocoro.jp/rensai
manga page: https://www.corocoro.jp/title/14
manga viewer page: https://www.corocoro.jp/chapter/617/viewer

note: this site use Shogakukan ID for purchase some episode

**Comment by MikeZeDev** [comment]
NextJS chunks craaaaaaaaaap ;-;
