### ISSUE TITLE
Help me, BOMTUN update code. 

### ISSUE THREAD

**Issue by Froktime** [manga-download/haruneko#810]
A new code was discovered this week. they limit the expiration time of the image link faster. I think if I take the data, can I get it from the canvas card of the image? No matter how many codes they change, the canvas is always the same. I'm sorry I don't know much about code, so that's what I thought. 
Test link (15+):   https://www.bomtoon.com/viewer/spinach_fl/p0

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/haruneko/issues/761
