### ISSUE TITLE
[Sushiscan] Chapters and / or volume are empty (no picutre available)

### ISSUE THREAD

**Issue by Kawik76** [manga-download/haruneko#814]
Hi;

I got an issue with most websites using cloudfare.

I tried with Haruneko (JW version) + assistant and also with Harukeno (Electron version), but  the problem happens in all cases.

For example with the connector sushiscan.net, I manage to get the manga and then the volume lists but when I click on the little eye icon to preview the images, the page is empty.
And if I try to download directly the volume, the cbz file is created but it is also empty...

Do you know if there is a way to solve this issue ?

Many thanks

**Comment by MikeZeDev** [comment]
This must be handled as a "per website" basis. You named sushiscan but no manga or chapter. Perhaps its not relevant , perhaps its CF, perhaps its only related to the website, but having manga and chapter name is very important.
