### ISSUE TITLE
Manga Galaxy | The connector shows the last 10 chapters on all the mangas

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#822]
https://mangagalaxy.net/home

All the mangas in the connector show the latest 10 chapters only (like from chap 130 - 139) and if a new chapter 140 drops then 130 will disappear.
![image](https://github.com/user-attachments/assets/9811df12-4aa5-4112-b49d-1d6896ee4554)

in the website you can see the previous chapters
![image](https://github.com/user-attachments/assets/117ed9b9-a5de-4b18-88bd-04cdff9f60d7)

**Comment by MikeZeDev** [comment]
Api returns 10 chapters but says there are 139 chapters, pffffff

**Comment by MikeZeDev** [comment]
Closed by https://github.com/manga-download/haruneko/commit/235db6c4c02c08ea038a1b5869e8f89146c4eafb
