### ISSUE TITLE
[JapScan.lol] Connector not working - Chapters are empty

### ISSUE THREAD

**Issue by Kawik76** [manga-download/haruneko#824]
Name of connector: https://www.japscan.lol/
Name of manga (if connector update is working: https://www.japscan.lol/manga/versus/
Name of chapter (if manga update is working): https://www.japscan.lol/lecture-en-ligne/versus/6/

Hi, 
I got an issue with the connector JapScan.lol
Using Haruneko + Assistant I manage to get the chapters list; but when I try to preview or download it it is empty..

Thanks in advance for your help :)
Kawik76

**Comment by MikeZeDev** [comment]
Having the error message would have helped

**Comment by Kawik76** [comment]
Would be nice if I had one indeed; but there is no error message... I can download the cbz file but it is empty.

Here I try to copy the console report : 

haruneko.pages.dev/:1 Error in event handler: TypeError: Cannot read properties of undefined (reading 'toggleFullscreen')
    at Shortcut.active (https://haruneko.pages.dev/M28SU49B/index.js:396:21733)
    at Shortcut.<anonymous> (extensions::nw.Shortcut:176:17)
    at Shortcut.emit (node:events:520:28)
    at extensions::nw.Shortcut:223:13
MediaTitleSelect.ts:325 C_<Frontend_Media_PasteLink_NotFoundError>: The provided link is not supported (a matching website was not found): https://www.japscan.lol/lecture-en-ligne/versus/6/
    at Je.<anonymous> (https://haruneko.pages.dev/M28SU49B/FrontendFluentCore.js:5721:617)
(anonymous) @ MediaTitleSelect.ts:325
await in (anonymous)
Dispatch @ Observable.ts:46
set Value @ Observable.ts:36
LoadMediaContainerFromURL @ RemoteProcedureCallContract.ts:13
(anonymous) @ InterProcessCommunication.ts:18
OnMessage @ InterProcessCommunication.ts:18
420Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
(index):1 Error in event handler: Error: No window with id: 605452099.
    at extensions::nw.currentWindowInternal:4:24
    at NWWindow.get (extensions::nw.Window:735:44)
    at NWWindow.<anonymous> (https://haruneko.pages.dev/M28SU49B/InteractiveFileContentProvider.js:1:1168)
    at NWWindow.<anonymous> (extensions::nw.Window:215:16)
    at dispatchEventIfExists (extensions::nw.Window:856:15)
    at onDocumentStartEnd (extensions::nw.Window:881:5)
RemoteBrowserWindow.ts:118 Uncaught (in promise) EvalError: <script>
    at X.ExecuteScript (RemoteBrowserWindow.ts:118:27)
    at NWWindow.<anonymous> (RemoteBrowserWindow.ts:75:18)
    at NWWindow.<anonymous> (extensions::nw.Window:215:16)
    at dispatchEventIfExists (extensions::nw.Window:856:15)
    at onDocumentStartEnd (extensions::nw.Window:881:5)Caused by: Error: No window with id: 605452099.
    at extensions::nw.currentWindowInternal:4:24
    at NWWindow.eval (extensions::nw.Window:481:42)
    at X.ExecuteScript (RemoteBrowserWindow.ts:116:34)
    at NWWindow.<anonymous> (RemoteBrowserWindow.ts:75:18)
    at NWWindow.<anonymous> (extensions::nw.Window:215:16)
    at dispatchEventIfExists (extensions::nw.Window:856:15)
    at onDocumentStartEnd (extensions::nw.Window:881:5)
ExecuteScript @ RemoteBrowserWindow.ts:118
(anonymous) @ RemoteBrowserWindow.ts:75
(anonymous) @ extensions::nw.Window:215
dispatchEventIfExists @ extensions::nw.Window:856
onDocumentStartEnd @ extensions::nw.Window:881
Promise.then
dB @ bowermisrule.com/gU1rcHRfCbUth/82490:1
dc.setState @ bowermisrule.com/gU1rcHRfCbUth/82490:1
ch.B.ch._ @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
setTimeout
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
await in (anonymous)
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
Y1 @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
dp @ bowermisrule.com/gU1rcHRfCbUth/82490:1
setTimeout
cp @ bowermisrule.com/gU1rcHRfCbUth/82490:1
requestAnimationFrame
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
d1.diffed @ bowermisrule.com/gU1rcHRfCbUth/82490:1
dz @ bowermisrule.com/gU1rcHRfCbUth/82490:1
du @ bowermisrule.com/gU1rcHRfCbUth/82490:1
dz @ bowermisrule.com/gU1rcHRfCbUth/82490:1
dP @ bowermisrule.com/gU1rcHRfCbUth/82490:1
bI @ bowermisrule.com/gU1rcHRfCbUth/82490:1
n.3645.n.exports @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(anonymous) @ bowermisrule.com/gU1rcHRfCbUth/82490:1
(index):1 Unchecked runtime.lastError: cannot find browser window

Dunno if that helps, let me know if you need anything else

**Comment by MikeZeDev** [comment]
> bowermisrule.com 

Either this error log is unrelated, either you got ** up by ads. Japscan is nasty and evil website, you dont imagine how much.

**Comment by Kawik76** [comment]
Well there's a billions ads on this website it's awful ; but they also have a lot of french chapters that are ony available here.. which is why it would be nice to be able to use it on Haruneko :p
