### ISSUE TITLE
[UI-Classic] MediaList overlaps on scroll

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#843]
there are 2 issues in bookmarks: 
1. when scrolling down on the bookmark list a big gap in the top section comes:
![image](https://github.com/user-attachments/assets/c6af0c7f-e8e9-4177-b23d-500edd7ac912)

2. The bookmarked manhwas are on top of each other (like there is no splitting line between them to keep this from happening):
![image](https://github.com/user-attachments/assets/5948687c-0fc4-48b2-9248-94c62a14f508)

**Comment by Sheepux** [comment]
Yup, it appeared when i changed the virtuallist component. the new one is buggy. I didn't have time to fix it yet

**Comment by Sheepux** [comment]
Fixed by https://github.com/manga-download/haruneko/commit/38cc85d36907e3423ee14cbe4ff04e82e2ec135f
