### ISSUE TITLE
Lezhin paste media link fail

### ISSUE THREAD

**Issue by reddy791** [manga-download/haruneko#850]
I moved from https://github.com/manga-download/hakuneko/issues/7530

I'm encountering an issue on LezhinUS where pasted media links do not display any content, despite being logged in. I pressed F12, and there appears to be an error, which I’ve added below. I noticed Lezhin recently updated its website, and I’m unsure if this issue is related or if a fix is in progress or if it occurs only me(but other connectors work fine), since I searched and didn't see anyone talking about it.

Link I copied: https://www.lezhinus.com/en/comic/cuzimcute

actions.ts:40 C_<Frontend_Media_PasteLink_NotFoundError>
at HTMLButtonElement.L [as __click] (https://haruneko.pages.dev/M2T4BUG4/FrontendClassic.js:26:8632)

**Comment by MikeZeDev** [comment]
They updated the website, indeed. I made a fix on [lezhin branch](https://github.com/manga-download/haruneko/tree/lezhin) and its was tested by some paid users as working but ill double check.

**Comment by MikeZeDev** [comment]
You are using haruneko from releases pages where many site plugins are not coded YET and are just placeholders. Lezhin is NOT PORTED yet. No wonder it doesnt work. No point in reporting things that are not coded yet.

Wait for [this ](https://github.com/manga-download/haruneko/pull/736) to be MERGED.
