### ISSUE TITLE
HaruNeko electron doesn't open

### ISSUE THREAD

**Issue by ShadowEaglz** [manga-download/haruneko#852]
Updated to hakuneko-electron-v32.1.2-win32-x64

when trying to start HaruNeko I get the followingerror message 
```
Error invoking remote method 'BloatGuard::Initialize': Error: No handler registered for 'BloatGuard::Initialize'
Error: Error invoking remote method 'BloatGuard::Initialize': Error: No handler registered for 'BloatGuard::Initialize'
```
![HaruNeko Bloat Message](https://github.com/user-attachments/assets/ba170413-2127-455a-8c55-a90eacc1210d)

**Comment by MikeZeDev** [comment]
Should i add : i cant launch prod electron from source code . dev electron works.

Not sure if related.

![image](https://github.com/user-attachments/assets/327fca11-8633-46d1-9808-b49ebc6e1e5c)

**Comment by ronny1982** [comment]
> Should i add : i cant launch prod electron from source code . dev electron works.
> 
> Not sure if related.
> 
> I ofc tested without my FW.

Not related.
Are you sure you are hosting with `serve:prod` and not `serve:dev`?

**Comment by ronny1982** [comment]
> Updated to hakuneko-electron-v32.1.2-win32-x64
> 
> when trying to start HaruNeko I get the followingerror message
> 
> ```
> Error invoking remote method 'BloatGuard::Initialize': Error: No handler registered for 'BloatGuard::Initialize'
> Error: Error invoking remote method 'BloatGuard::Initialize': Error: No handler registered for 'BloatGuard::Initialize'
> ```
>

There was a fixed typo, which is still present in the latest release but already updated in the web-application.
Need to wait for next client release which i was hoping to delay until the external NW crash bug https://github.com/nwjs/nw.js/issues/8205 was solved.

**Comment by ronny1982** [comment]
New desktop client release was deployed

**Comment by MikeZeDev** [comment]
I seems like my problem was a race condition. nvm
