### ISSUE TITLE
I can't open Haruneko

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#863]
I'm not able to open Haruneko. I even re-downloaded it but it just sits in Task Manager. is there anything I have to do.
![image](https://github.com/user-attachments/assets/6a6d2782-1ace-4f62-b3f4-97ba2afbe60e)

**Comment by MikeZeDev** [comment]
I am sorry you havent been answered yet but i have no clue about what going on. And this screenshot gives no useful informations at all. What about Electron version?
