### ISSUE TITLE
Problem Resource is not a Image

### ISSUE THREAD

**Issue by Frezian** [manga-download/haruneko#872]
Unable to display images on the Ikiru and Kiryuu source
![Screenshot 2024-11-12 144901](https://github.com/user-attachments/assets/eeb5e046-b007-4c0a-a2d1-c71dfd6595b5)

**Comment by MikeZeDev** [comment]
See that? 
![image](https://github.com/user-attachments/assets/68574539-fba2-416f-96f6-eb9fb47a0b8c)

Servers says "application/octet-stream" when requesting images. Meaning its a shitty server and we have to manually detect image type. It doesnt affect download except for file extension, you can just rename them as "jpeg" or whatever.
