### ISSUE TITLE
Cannot Load Manga List MgKomik

### ISSUE THREAD

**Issue by Frezian** [manga-download/haruneko#875]
I can't access the comic list on MgKomik, even though I tried using Hakuneko Assistant. It works on other websites, but not on MgKomik. Do you have a solution?

![Screenshot 2024-11-14 081320](https://github.com/user-attachments/assets/db07486c-cd08-42a9-aadd-9fb0df964905)

**Comment by MikeZeDev** [comment]
Read message follow instructions.
