### ISSUE TITLE
[Booklive] Connector not working

### ISSUE THREAD

**Issue by kskase** [manga-download/haruneko#887]
I used the link https://booklive.jp/product/index/title_id/811278/vol_no/045 from the clipboard within Haruneko, but no response.

To Reproduce
Name of connector: Booklive
Name of manga: Every

Note : It's still work properly with old Hakuneko version.
![image](https://github.com/user-attachments/assets/39d42d73-de6b-4e40-954d-0a07767ef8af)

**Comment by MikeZeDev** [comment]
Use the correct github 😮‍💨
