### ISSUE TITLE
{Website module request} [Lezhin Spanish]

### ISSUE THREAD

**Issue by CloudBladed** [manga-download/haruneko#89]
Name: Lezhin

Root URL: https://www.lezhin.es/

Example manga info URL: https://www.lezhin.es/detail/la-que-florece-en-el-invierno

Example chapter URL: https://www.lezhin.es/viewer/la-que-florece-en-el-invierno/1

Language: Spanish

**Comment by Sheepux** [comment]
not the place to request, use hakuneko github
https://github.com/manga-download/hakuneko
