### ISSUE TITLE
Multiple Right-Click Bug

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#890]
Just discovered I can right-click on multiple mangas and the previous one will not disappear:

![image](https://github.com/user-attachments/assets/c41ecc45-6c08-4618-a75b-df8179c8bcfc)

**Comment by Sheepux** [comment]
fixed by commit https://github.com/manga-download/haruneko/commit/488b1b61dd2c1a66c73b040a8f04161bf8536d12
