### ISSUE TITLE
[Asura Scans] Manga Syntax error

### ISSUE THREAD

**Issue by Noonereallycomeon** [manga-download/haruneko#891]
Demon King Manhwa
https://asuracomic.net/series/demon-king-a983671b
gives SyntaxError
Unexpected non-whitespace character after JSON at position 21 (line 1 column 22)

None of my other bookmarks have this problem.

**Comment by ShamsEE96** [comment]
![112](https://github.com/user-attachments/assets/09f9b7c4-d29b-418d-a54a-8f04ddfd8621)
just to add to this issue
some other give this error instead :
```
SyntaxError

Unexpected non-whitespace character after JSON at position 2 (line 1 column 3)
```

**Comment by MikeZeDev** [comment]
🤦 I have asura so much
