### ISSUE TITLE
Chapter Number and Title Spacing

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#895]
There is no spacing between the chapter number and title. But in the website there is:

![image](https://github.com/user-attachments/assets/7744f629-0595-408d-b7e7-66c5d360ba04)

![image](https://github.com/user-attachments/assets/1f3cc04c-2c03-46ba-81f7-f1e51b932324)

![image](https://github.com/user-attachments/assets/6098ad31-2c95-4f7b-89a0-c2bcdcca051a)

I'm sorry I'm using AsuraScans a lot as an example (because I use them more often)😅. but it happens in other websites

**Comment by MikeZeDev** [comment]
*Burn asura with fire*

**Comment by MikeZeDev** [comment]
If its happening to other website name other website because its a per website issue

**Comment by Sheepux** [comment]
Can't you just parse it nicely and add yourself a space if that's a repeating pattern for that plugin ??
