### ISSUE TITLE
Hakuneko not working

### ISSUE THREAD

**Issue by usegaha** [manga-download/haruneko#900]
When I install and open the shortcut it only shows a white screen and I can't close it too. How do I fix it? I'm using the 64bit version for window

**Comment by Sheepux** [comment]
Hakuneko or Haruneko ?

**Comment by Sheepux** [comment]
Try to disable your firewall. We had the same issue with haku and most of the time it was the antivirus/antimalware denying the localhost server (hakuneko is using a local server + chrome UI)
