### ISSUE TITLE
Cbz download image out of order and timeout error on Japscan

### ISSUE THREAD

**Issue by PerseusRex** [manga-download/haruneko#909]
Downloading from Japscan results in a timeout error.
`The request could not be fulfilled within the given timeout!
l1<FetchProvider_FetchWindow_TimeoutError>
    at https://haruneko.pages.dev/M41PU3T2/InteractiveFileContentProvider.js:2:982`
It looks like occasionally it would also be 
`The access to "https://c4.japscan.lol/b762e622a032c1b2b19597621982a4422892f2526335a0b2f18572758272a2029932e5b21912a732c2421392e1f25/3124245f9e2774262a248b236f2f9b2a482915554b247c2e98255e2058223b2e662ap92342501f6f4d66356f0c58q/55b63528d582666r62866559b66m35bqa19862a22211f26r7174a22q01d232c6c2dr01bq63er23a833c1b4br93976/31r81.jpg" was denied. Make sure the website is available and accessible (e.g., VPN to bypass region lock, manual login via website link).
l1<FetchProvider_Fetch_Forbidden>
    at Ae.ValidateResponse (https://haruneko.pages.dev/M41PU3T2/InteractiveFileContentProvider.js:1:4288)
    at Ae.Fetch (https://haruneko.pages.dev/M41PU3T2/InteractiveFileContentProvider.js:2:3930)
    at async yu.action (https://haruneko.pages.dev/M41PU3T2/HakuNeko.js:1:15936)
    at async yu.Run (https://haruneko.pages.dev/M41PU3T2/index.js:2:30062)
    at async Eo.Run (https://haruneko.pages.dev/M41PU3T2/index.js:2:31577)`
But I can still access the page on my browser.

I did manage to download from Japscan last week, but didn't check the download until today. The cbz file that downloaded has the images out of order.

**Comment by MikeZeDev** [comment]
A manga and chapter would have helped.

**Comment by PerseusRex** [comment]
Sorry, forgot to include that. An example would be 
https://www.japscan.lol/manga/radiant/
https://www.japscan.lol/lecture-en-ligne/radiant/volume-1/

I can't check the order now because it's throwing either of those two errors I listed, but the website itself, the order looks to be correct and I do remember the preview I saw when it was working last week was the right order as well.

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/20f362c7-f245-4012-a6b6-34cc1cb00fdf)

I dont have your 403 error, most likely you were blocked by Japscan. Try with a VPN or something.

There is another error i must investigate , i got this when trying to download

![image](https://github.com/user-attachments/assets/e7f054fd-bbc6-445f-a2f4-23932fb9f0ef)

**Comment by PerseusRex** [comment]
Sorry this might sound like a dumb question. But do you know if there's a way around the block? Is it cloudflare that's blocking me or Japscan itself? Because either way the website itself works fine when I'm on chrome, it doesn't load in Haruneko. I do believe I was using a VPN when I was downloading and have switched around different servers, but they all show the same error in Haruneko.  Some servers  actually does give a "You are blocked" page in my browser and others are fine. But none of them let's Haruneko load the pages.

**Comment by MikeZeDev** [comment]
You may get this blocking screen for many reasons and there is no magic bypassing it. 
Its could be blocking by IP, Ip range, country, anything that they dont like in requests, perhaps you were rate limited and must wait a bit 🤷 

First make sure you use Electron build as it seems CF is less sensible to it. Play with VPN is the only advice you can get.
Use fluent core interface in setting so it has a button to open website in a browser window, and you can click on a manga / chapter to trigger and fill CF captcha to grant access to manga pages or chapters pages. 🤷
