### ISSUE TITLE
Request site: Manga One

### ISSUE THREAD

**Issue by sakuhanachan** [manga-download/haruneko#915]
Site: https://manga-one.com/  
Manga List: https://manga-one.com/rensai  
Manga example: https://manga-one.com/viewer/188243  
Chapter online viewer example: https://manga-one.com/viewer/188243  

Website relationship: Web version of Shogakukan's Manga One App, update chapter faster then Ura Sunday 1 chapter.

**Comment by MikeZeDev** [comment]
Protobuff

**Comment by Sheepux** [comment]
Please open site request in hakuneko's repo. We need to keep this repo only for bugs.
