### ISSUE TITLE
Asura+ + Haru = Issue+??

### ISSUE THREAD

**Issue by Noonereallycomeon** [manga-download/haruneko#929]
Nothing happens when an asura chapter is selected no error is shown, also asura now has subscription, is it gonna get worse?

**Comment by MikeZeDev** [comment]
You must know that Asura is coded in a way where the little change they make will always break scrapers.
If you are familiar with asura you know its not uncommon :D

If it doesnt work open a proper issue and dont ask stuff we cant answer?  :D
