### ISSUE TITLE
manga.bilibili.com can't download

### ISSUE THREAD

**Issue by apt42541** [manga-download/haruneko#932]
![image](https://github.com/user-attachments/assets/0fae5fc7-0e79-423a-b4d3-24e9e73a0bd2)

from this connector : https://manga.bilibili.com/detail/mc33774

**Comment by MikeZeDev** [comment]
Why does people keep posting issuer for haKUneko in haRUneko github?

**Comment by apt42541** [comment]
i dont post  issues for haKUneko in haRUneko github, but i try both hakuneko and haruneko. so i give log in two program.

**Comment by MikeZeDev** [comment]
> i dont post issues for haKUneko in haRUneko github, but i try both hakuneko and haruneko. so i give log in two program.

Your screen is a ha**KU**neko screenshot, describing an ha**KU**neko issue and we are currently in is ha**RU**neko repository

Therefore, its invalid. This twice before saying nonsense pls.
