### ISSUE TITLE
[Sushi Scans (NET)] Error in chapter image retrieve

### ISSUE THREAD

**Issue by arcanaXknight** [manga-download/haruneko#937]
Hello, 

First time publishing something so i'll try to be clear.
I tried to use Haruneko with "Sushi Scans (NET)" connector.

When using "Hakuneko assistant" bypassing cloudflare works fine.
I could get manga list and chapter list for a selected entry.

But when i tried to open or download any chapter in chapter list i get an error named : "Nothing to show: content list is empty.".

![Capture](https://github.com/user-attachments/assets/2aba05b2-c884-4b22-828b-4501b3fda609)

Seems like the website change his way of managing image.

Have a nice day.

Arcana

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/9362f184-f378-4c4b-a52d-0abc176c62da)

I am afraid it still works. Maybe your CF cookie was rejected. Perhaps use Electron build to deal with CF websites?

**Comment by arcanaXknight** [comment]
So,

First of all, sorry to bother you with something that works.

I tried to delete everything, upgrade node and clone git and it work with app launch in electron.

I cannot connect directly through localhost:5000 (Failed to create an instance of type <T> for platform 'chromium'!)
but app works.

**Comment by MikeZeDev** [comment]
No pb.

> localhost:5000 (Failed to create an instance of type for platform 'chromium'!)

That is expected. We reject loading from Chrome or Firefox as it wouldn't work ^^

What i meant is that CloudFlared websites can be hell to deal with so you may expect some random problem like that.
It would have been interesting to see what error did you get in console or network tab.

If its fixed then feel free to close this.
