### ISSUE TITLE
[spiderscans] chapter list does not appear

### ISSUE THREAD

**Issue by Mammad211** [manga-download/haruneko#938]
https://spiderscans.xyz/manga/ manga list isn't working they had some changes recently

**Comment by MikeZeDev** [comment]
![image](https://github.com/user-attachments/assets/7fe9207e-6d1a-49f4-a44c-067f8eaec89a)

It doesnt even load in browser what do you expect?  :D

**Comment by MikeZeDev** [comment]
template change....
