### ISSUE TITLE
New Bato domain causes application to become unresponsive

### ISSUE THREAD

**Issue by kamiTT** [manga-download/haruneko#945]
When I paste a link from the new bato domain the entire application becomes unresponsive, requiring me to force quit the application. I've attempted to wait it out, but I gave up after leaving the application alone for an hour.

Some background:
Client:  hakuneko-electron-v33.0.2-darwin-x64
OS: macOS Sonoma 14.7.2

When I paste the url, no console error appears.
I've tried to run the application locally, but I'm definitely missing something because I can't get the UI to appear

**Comment by MikeZeDev** [comment]
xbato uses Cloudflare.

Either you 
* Pass the cloudflare cookie to Haruneko using Haruneko Assistant BEFORE ANY INTERACTION WITH BATOTO IN HARUNEKO

or

* You use Haruneko electron build 
 
Its a NWJS bug we cant do anything about it
