### ISSUE TITLE
Reaper Scans Chapter titles

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#955]
Hi, could you please add the chapter titles for Reaper Scans manhwas. 

i.e. https://reaperscans.com/series/return-of-the-frozen-player

![image](https://github.com/user-attachments/assets/f81fcad4-538b-447d-be13-e1ea2489dcbe)

all of them use the same span class.

**Comment by MikeZeDev** [comment]
Not a reaper use myself, and most of chapters dont have anything. No wonder i didnt saw that.
![image](https://github.com/user-attachments/assets/1861fbea-a980-4f76-8d47-b96b916bbc06)
