### ISSUE TITLE
Set-Cookie in response issue

### ISSUE THREAD

**Issue by MikeZeDev** [manga-download/haruneko#98]
Case: 

URL 1 : https://mangayeh.com/chapter/cheat-kusushi-no-slow-life-isekai-ni-tsukurou-drugstore/chapter-44

This url redirect (302) to

URL 2 :  https://gamesk.pro/chapter/cheat-kusushi-no-slow-life-isekai-ni-tsukurou-drugstore/chapter-44?t=db2ef9772b744e93ac21d023d74e6446e1612014959. 

Then there is another redirection on URL2 (302 again) which is 

URL3 : https://gamesk.pro/games/d/serial-cleaners-459051 (randomized)

In browser, URL3 behave differently if you open it in a new tab than if you followed redirections.

Direct access : ads for videogames
Redirected access  :  page with chapters pictures.

![image](https://user-images.githubusercontent.com/10671518/219958404-f01ef1a2-6069-492b-86e6-47eb92d1fe41.png)

If the last request, Firefox got JSESSION in cookies, which Haru didnt. Cookie which should have been added according to the 'Set-Cookie' directive in PREVIOUS Request response, even if the response code was 302.

This may definitely be this JSESSION cookie that we miss. That and maybe referer (but i added it and it doesn't change anything) or the cloudflare cookie (that will be a problem). 

In any case, we should have seen JSESSION cookie in last request i guess.

### Solution ; 

Intercept the requests response (with a handler) and set the cookie.

**Comment by ronny1982** [comment]
I [fixed a timeout issue](https://github.com/manga-download/haruneko/commit/8e830d0f2aa46b8abf0d1b0914c2f4f4b36983bd) with `FetchWindowCSS`.
It is expected that cookies are now correctly set and image links can be extracted from a chapter.

```typescript
console.log('Cookies (before):', await chrome.cookies.getAll({}));
const request = new FetchRequest('https://mangayeh.com/chapter/cheat-kusushi-no-slow-life-isekai-ni-tsukurou-drugstore/chapter-44', {});
const data = await FetchWindowCSS<HTMLImageElement>(request, '.container p img[data-src]', 2500);
console.log('Cookies (after):', await chrome.cookies.getAll({}));
console.log('Images:', data.map(img => img.dataset.src));
```

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/27136773/221345317-10666549-1f64-492f-8c0b-77be464f6875.png">

**Comment by MikeZeDev** [comment]
Nice to see, i suspected something like that because JSESSION i setup using my code was in storage but old JSESSION from prvious test was still send. gotta test it <3

**Comment by MikeZeDev** [comment]
Fixed by https://github.com/manga-download/haruneko/commit/8e830d0f2aa46b8abf0d1b0914c2f4f4b36983bd
